# Import the built-in Django User model
from django.contrib.auth.models import User

# Import serializers from Django REST Framework (DRF)
# Serializers are like translators: they convert Python objects (like our models)
# into JSON format (so the frontend can read it) AND convert JSON from the frontend
# back into Python objects (so we can save them to the database).
from rest_framework import serializers

# Import our custom models
from .models import Category, Transaction

# =====================================================================
# USER REGISTRATION SERIALIZER
# Translates data from the registration form into a new User object.
# =====================================================================
class UserRegistrationSerializer(serializers.ModelSerializer):
    """
    Serializer to handle user registration.
    Converts incoming JSON (username, password) into a Django User instance.
    """
    # We explicitly define the password field here because we need to add special rules.
    password = serializers.CharField(
        write_only=True, # VERY IMPORTANT: The password can be written, but NEVER read back in JSON!
        required=True,   # You can't register without a password.
        style={'input_type': 'password'} # Tells the frontend it's a password field.
    )

    class Meta:
        # We are translating the built-in User model.
        model = User
        # We only care about saving the username and password right now.
        fields = ('username', 'password')

    # This method is called automatically when we do `serializer.save()`.
    def create(self, validated_data):
        # We use `create_user` instead of just saving the model normally.
        # This is CRITICAL because `create_user` securely hashes the password 
        # (turns "mycat123" into an unreadable string of gibberish) before saving it to the database!
        user = User.objects.create_user(
            username=validated_data['username'],
            password=validated_data['password']
        )
        return user


# =====================================================================
# CATEGORY SERIALIZER
# Translates Category objects to/from JSON.
# =====================================================================
class CategorySerializer(serializers.ModelSerializer):
    """
    Serializer for the Category model.
    The user field is read-only because the backend automatically assigns it.
    """
    class Meta:
        # We are translating the Category model.
        model = Category
        # The fields we want to expose in our API endpoints.
        fields = ('id', 'user', 'name', 'type')
        # We mark 'user' as read_only. This means the frontend can see the user_id,
        # but if a hacker tries to send a PUT request saying {"user": 999}, the 
        # serializer will completely ignore it, protecting other users' accounts!
        read_only_fields = ('user',)


# =====================================================================
# TRANSACTION SERIALIZER
# Translates Transaction objects to/from JSON.
# =====================================================================
class TransactionSerializer(serializers.ModelSerializer):
    """
    Serializer for the Transaction model.
    Includes custom validation to ensure the category belongs to the user making the request.
    """
    class Meta:
        # We are translating the Transaction model.
        model = Transaction
        # The fields we want to expose. 'id' is automatically generated by Django.
        fields = ('id', 'user', 'amount', 'date', 'description', 'category')
        # Same security rule as the category: the frontend cannot change who owns this transaction.
        read_only_fields = ('user',)

    # This is a custom validation hook. 
    # It runs automatically when the frontend tries to save a transaction.
    def validate_category(self, value):
        """
        Ensure the selected category actually belongs to the user making the request.
        """
        # self.context['request'] gives us access to the HTTP request, which contains the logged-in user.
        request = self.context.get('request')
        
        # If there's a logged-in user, but the category they are trying to use
        # doesn't belong to them, we crash the request with a ValidationError.
        # This prevents "Insecure Direct Object Reference" (IDOR) attacks!
        if request and hasattr(request, 'user'):
            if value.user != request.user:
                raise serializers.ValidationError("You can only use your own categories.")
                
        # If everything is fine, return the category back to the serializer.
        return value
